services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: nakama
      POSTGRES_PASSWORD: localdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nakama"]
      interval: 5s
      timeout: 5s
      retries: 10

  nakama:
    image: heroiclabs/nakama:3.21.1
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "7350:7350"   # HTTP API
      - "7351:7351"   # Console Web UI
      - "7352:7352"   # gRPC
    environment:
      GAME_SERVER_ADDR: "8.130.49.62:7777"
    volumes:
      - ./modules:/nakama/data/modules
    entrypoint:
      - /bin/sh
      - -c
      - |
        /nakama/nakama migrate up --database.address "postgres:localdb@postgres:5432/nakama"
        exec /nakama/nakama --database.address "postgres:localdb@postgres:5432/nakama" --logger.level DEBUG --runtime.js_entrypoint index.js

volumes:
  pgdata:
